export type GunTypes = "Pistol" | "Submachine Gun" | "Shotgun" | "Combat Rifle" | "Sniper Rifle" | "Rocket Launcher" | undefined;
export type GuildTypes = "Alas!" | "Skuldugger" | "Dahlia" | "Blackpowder" | "Malefactor" | "Hyperius" | "Feriore" | "Torgue" | "Stoker" | undefined;
export type RarityTypes = "Common" | "Uncommon" | "Rare" | "Epic" | "Legendary";
export type ElementTypes = "Incendiary" | "Incendiary (+1d6)" | "Incendiary (+2d6)" | "Shock" | "Shock (+1d6)" | "Shock (+2d6)" | "Corrosive" | "Corrosive (+1d6)" | "Corrosive (+2d6)" | "Cryo" | "Cryo (+1d6)" | "Cryo (+2d6)" | "Explosive" | "Explosive (+1d6)" | "Explosive (+2d6)" | "Radiation" | "Radiation (+1d6)" | "Radiation (+2d6)" | "Radiation + Incendiary" | "Shock + Corrosive" | "Explosive + Cryo" | "N/A"
export type PrefixTypes = "Aback" | "Aberrant" | "Abhorrent" | "Abiding" | "Abrasive" | "Actually" | "Adhesive" | "Adorable" | "Bitter" | "Boundless" | "Breezy" | "Certain" | "Cheerful" | "Classy" | "Clever" | "Critical" | "Damp" | "Deafening" | "Disgusted" | "Eatable" | "Economic" | "Elfin" | "Exciting" | "Far-Flung" | "Far" | "Few" | "Fresh" | "Frightening" | "Gaudy" | "Grey" | "Grotesque" | "Handsomely" | "Holistic" | "Honorable" | "Horrible" | "Humdrum" | "Hysterical" | "Imaginary" | "Imminent" | "Impolite" | "Incandescent" | "Jazzy" | "Joyous" | "Jumbled" | "Knotty" | "Knowing" | "Labored" | "Legal" | "Light" | "Lively" | "Mad" | "Madly" | "Mixed" | "Mundane" | "Normal" | "Nutty" | "Obnoxious" | "Obtainable" | "One" | "Open" | "Overconfident" | "Panoramic" | "Parallel" | "Practical" | "Pumped" | "Puny" | "Questionable" | "Relevant" | "Resolute" | "Same" | "Scintillating" | "Selfish" | "Several" | "Shaky" | "Sleepy" | "Small" | "Smelly" | "Splendid" | "Strong" | "Stupendous" | "Suitable" | "Superb" | "Swift" | "Synonymous" | "Tart" | "Tawdry" | "Tender" | "Tense" | "Thirsty" | "Toothsome" | "Towering" | "Two" | "Unable" | "Unfair" | "Unwieldy" | "Utter" | "Woozy" | "Worried" | "Wrathful" | "Zesty" | undefined;
export type RedPrefixTypes = "POP POP!" | "I never freeze" | "Toasty!" | "Was he slow?" | "We Hate You, Please Die." | "Tell them they're next" | "PAN SHOT!" | "Envision Wyverns" | "I'm melting!" | "The same thing that happens to everything else" | "360 quickscope" | "Any Questions!" | "Blood and Thunder" | "SI VIS PACEM, PARA BELLUM" | "You're breathtaking!" | "Pass turn." | "I am Vengeance!" | "Roll the dice" | "One among the fence" | "Don't be sorry. Be better." | "THE PICKLES!" | "Do a kickflip!" | "Extinction is the Rule" | "Never Fight a Knight with a Perm" | "Bye bye, little Butt Stallion" | "Time 2 Hack" | "Hate Magic... so much" | "OFF WITH THEIR HEADS!" | "This is my BOOMSTICK!" | "Super easy, barely an inconvenience" | "Hold onto your butts." | "The Wise Man's Fear" | "I don't want this isolation" | "TUFF with two Fs" | "Unlikely Maths" | "Gravity's Rainbow" | "Let's do this one last time..." | "BIP!" | "The Heaviest Matter of the Universe" | "GREEN FLAME" | "More like Bore Ragnarok!" | "That's levitation, Holmes!" | "Let's boo-boo." | "Mmm Watcha Say..." | "Here Comes the FunCooker" | "Overwhelming strength is boring." | "Stop talking, I will win. It's what heroes do." | "Richer and cleverer than everyone else!" | "METAL WILL DESTROY ALL EVIL!" | "Life is conundrum of esoterica" | undefined;
export interface GunCard {
    level: number;
    type: GunTypes;
    guild: GuildTypes;
    rarity: RarityTypes;
    element: ElementTypes
    prefix?: PrefixTypes | RedPrefixTypes;
}